config/routes.rb
Rails.application.routes.draw do


  get 'books/book'
  get '/about',to: 'users#about'

  devise_for :users, controllers: {
    confirmations: 'devise/confirmations',
    passwords:     'devise/passwords',
    registrations: 'devise/registrations',
    sessions:      'devise/sessions',
  }
  # devise_for :users
  resources :users, only: [:index, :show]
  resources :posts
  root 'users#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    include ImageUploader[:image]
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

      def configure_permitted_parameters
        added_attrs = [ :name,:email, :password, :password_confirmation]
        devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
        devise_parameter_sanitizer.permit :account_update, keys: added_attrs
        devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
      end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def book
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end
  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))

    if @post.save
      redirect_to post_path(@post)
    end
  end

  def index
    @posts = Post.all
  end



  def show
    @post = current_user.posts.find(params[:id])
  end

  def edit
    @post = current_user.posts.find(params[:id])


  end

  def update
    @post = current_user.posts.find(params[:id])
    @post.update!(post_params)
    redirect_to post_path(@post)
  end
  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  private

    def post_params
      params.require(:post).permit(:title, :content,:image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def about
  end

  def home
  end

  def index

  end

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/book.html.slim
h1 Books#book
p Find me in app/views/books/book.html.slim

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
    .container
        nav
            ul.nav.navbar-nav.navbar-right
                - if user_signed_in?
                    li = link_to 'home',root_path
                    li = link_to 'about',about_path
                    li = link_to 'index',users_path
                    / devise関連
                    li = link_to '新規投稿',new_post_path
                    li = link_to '投稿一覧',posts_path
                    li = link_to 'プロフィール', current_user
                    li = link_to 'ログアウト', destroy_user_session_path , method: :delete
                - else
                    li = link_to 'log in',new_user_session_path
                    li = link_to 'sign up',new_user_registration_path
                    li = link_to 'Forgot your password?',new_user_password_path
                    li = link_to '編集',edit_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | BookApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    p.notice = notice
    p.alert = alert
    = render 'layouts/header'
    = yield
    = debug(params) if Rails.env.development?

app/views/posts/_form.html.slim
= form_with model: @post, local: true do |f|
    .field
        = f.label :title
        br
        = f.text_field :title, class: 'form-control'
    .field
        = f.label :content
        br
        = f.text_field :content, class: 'form-control'
    .field
        = f.label :image_data
        = f.hidden_field :image, value: @post.cached_image_data
        = f.file_field :image
    = f.submit nil, class: 'btn btn-primary'

app/views/posts/edit.html.slim
h1 edit

= render "posts/form"

app/views/posts/index.html.slim
h1 Post一覧

= link_to "新規投稿",new_post_path, class: 'btn btn-primary'

.mb-3
table.table.table0-hover
    thead.thead-default
        tr
            th  title
            th  content
            th  user_id
        tbody
            - @posts.each do |post|
                tr
                    td = link_to post.title ,post_path(post)
                    td = post.content
                    td = post.user_id
                    td
                        = link_to '編集',edit_post_path(post),class: 'btn btn-primary mr-2 '
                        = link_to '消去',post, method: :delete,class: 'btn btn-danger'

app/views/posts/new.html.slim
h1 POST 新規投稿

= render "posts/form"

app/views/posts/show.html.slim
h1 Post_show

table.table.table-hover
 tbody
    tr
        th user_id
        td = @post.user_id
    tr
        th ID
        td = @post.id
    tr
        th Title
        td = @post.title
    tr
        th content
        td = @post.content
    tr
        th  image
        td = image_tag  @post.image[:small].url
    tr
        th created
        td = @post.created_at
    tr
        th updated
        td = @post.updated_at

= link_to 'edit',edit_post_path,class: 'btn btn-primary'
= link_to 'destroy',@post, method: :delete,class: 'btn btn-danger'

app/views/users/about.html.slim
p
    | このサイトはただひたすらおすすめの本を紹介し続けるサイトです

app/views/users/home.html.slim
h1　 この本マジでオススメ
p おすすめの本を紹介するサイト

app/views/users/index.html.slim
h1 Users#index
p Find me in app/views/users/index.html.slim

app/views/users/show.html.slim
h1 Users#show
p Find me in app/views/users/show.html.slim
= @user.name
br
= @user.email